### ISSUE TITLE
404 not found - "sprites.[contenthash].svg "

### ISSUE THREAD

**Issue by jsauca** [stldo/gatsby-plugin-svg-sprites#5] opened 2021-09-03 13:17 UTC
Hi,

I have had this issue for a while now. When my Gatsby site rebuilds using existing cache the newly generated sprite is not found. 

Console log error > "GET https://***/sprites.[contenthash].svg net::ERR_ABORTED 404"

As per the console log error, it seems the "contenthash" is not applied to the sprite name. 
The only way I have found to fix this issue is to clean the cache before the build.

This issue occurs in both development and production modes.

package.json
- "gatsby": "3.12.1",
- "gatsby-plugin-svg-sprites": "0.0.2"

Thanks for your help.

**Comment by stldo** [comment] 2021-09-09 23:41
Hi! Thanks for reporting! I tried to reproduce this issue but I was unable to. Do you mind testing it on Gatsby 3.13? This issue can be related to webpack caching in development, released in Gatsby 3.12/3.13. While this issue isn't fixed, you can try disabling it to see if it works, just set `PRESERVE_WEBPACK_CACHE` to false.

**Comment by jsauca** [comment] 2021-09-15 10:22
Hi  @stldo ,

Thanks for your help. 

I have updated Gatsby to 3.13 and set the PRESERVE_WEBPACK_CACHE flag to false. Development and production modes are now working however there is still issues; see my network log:

**In development mode:**
- Sprite is successfully loaded but it also tried to load two additional sprites.[contenthash].svg which fails (404)
![Screen Shot 2021-09-15 at 8 11 37 pm](https://user-images.githubusercontent.com/29192645/133415458-f3bcf11b-0f1f-45fe-ac7a-97629ec30e01.png)

**In production:**
- Two svg sprites are loaded.  Their content is identical,  they just have different contenthash.
![Screen Shot 2021-09-15 at 8 16 19 pm](https://user-images.githubusercontent.com/29192645/133415734-19588df0-0b1a-4f13-8988-c74449419746.png)

I am not sure what is the issue here. It seems to be related to webpack but can't figure it out!

**Comment by stldo** [comment] 2021-09-17 04:07
Nice, it seems that there's an issue with the cache, but there is still another issue. I couldn't reproduce the errors you are getting. Do you mind sharing the plugins that are activated in `gatsby-config.js`? Are you making any modifications to Gatsby configuration inside `gatsby-node.js`?

**Comment by stldo** [comment] 2022-02-15 04:30
Since Gatsby v3 is not supported by this plugin anymore, I'm closing this issue.

**Comment by stldo** [comment] 2022-03-04 20:14
I found a way to reproduce this bug, so I'll reopen this issue until it's fixed.

**Comment by stldo** [comment] 2022-03-09 18:41
There's an issue with the underlying webpack plugin that makes the loader generate the source before the plugin generates the paths to the sprites file. I'm very busy right now to properly find and fix this issue, but I added the `randomContentHash` (https://github.com/stldo/gatsby-plugin-svg-sprites/commit/954a1bbb670802b2820606c6971573291bd22881) as a way to circumvent it. For more info, please check https://github.com/stldo/gatsby-plugin-svg-sprites#known-issues.

**Closed as completed by stldo** 2022-03-09 18:41 UTC
